[package]
name = "check_article_review"
version = "0.1.0"
edition = "2024"

[dependencies]
regex = "1.11.1"
reqwest = "0.12.15"
tokio = { version = "1.44.2", features = ["rt", "rt-multi-thread", "macros"] }
